apiVersion: apps/v1
kind: Deployment
metadata:
  name: golf-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golf-app
  template:
    metadata:
      labels:
        app: golf-app
    spec:
      containers:
      - name: golf-app
        image: gcr.io/golf-app-project-416715/golf_app
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: MYSQL_HOST
          value: "mysql-db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "P@ssword"
        - name: MYSQL_DATABASE
          value: "golf_db"
        - name: POSTGRES_HOST
          value: "postgres-db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "P@ssword"
        - name: POSTGRES_DB
          value: "postgres"

---

apiVersion: v1
kind: Service
metadata:
  name: golf-app
spec:
  selector:
    app: golf-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: gcr.io/golf-app-project-416715/worker_app
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_HOST
          value: "mysql-db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "P@ssword"
        - name: MYSQL_DATABASE
          value: "golf_db"
        - name: POSTGRES_HOST
          value: "postgres-db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "P@ssword"
        - name: POSTGRES_DB
          value: "postgres"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: gcr.io/golf-app-project-416715/mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssword"
        - name: MYSQL_DATABASE
          value: "golf_db"

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: gcr.io/golf-app-project-416715/postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "P@ssword"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/golf-app-project-416715/nginx
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer