apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: gcr.io/golf-app-project-416715/worker_app:v1.0
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_HOST
          value: "mysql_db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "P@ssword"
        - name: MYSQL_DATABASE
          value: "golf_db"
        - name: POSTGRES_HOST
          value: "postgres_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "P@ssword"
        - name: POSTGRES_DB
          value: "postgres"

---

