# Use an official PostgreSQL image as a parent image
FROM postgres:latest

# Copy the initialization SQL script into the container
COPY init_postgres.sql /docker-entrypoint-initdb.d/

# Define environment variables
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expose port 
EXPOSE 5432